"""added question index field in Interview model

Revision ID: 8fa7abcbe0fd
Revises: 089f3c3c9052
Create Date: 2026-02-13 12:29:43.161501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa7abcbe0fd'
down_revision: Union[str, Sequence[str], None] = '089f3c3c9052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### add column with server default
    op.add_column('interviews', sa.Column(
        'current_question_index',
        sa.Integer(),
        nullable=False,
        server_default='1'
        )
    )
    # ### end Alembic commands ###

    # Remove server default(optional)
    op.alter_column(
        'interviews',
        'current_question_index',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'current_question_index')
    # ### end Alembic commands ###
