"""Added fields to Interview

Revision ID: a25afc680897
Revises: 8fa7abcbe0fd
Create Date: 2026-02-16 12:14:28.105050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25afc680897'
down_revision: Union[str, Sequence[str], None] = '8fa7abcbe0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('total_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('max_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('percentage_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'percentage_score')
    op.drop_column('interviews', 'max_score')
    op.drop_column('interviews', 'total_score')
    # ### end Alembic commands ###
